SuffolkLITLab/ALKiln

lib/github_integration/install-branch.js
lib/steps.js
package.json

Not sure this was the problem, but if it was, this fixes it.

Trigger test.yml generation before pulling project

---

lib/github_integration/install-branch.js
lib/steps.js
lib/utils/env_vars.js
package.json

Working for https://github.com/GBLS/docassemble-MAEvictionDefense currently

Throw error on setup failure, add new branch name management

---

lib/scope.js
lib/steps.js
package.json
pushing_testing_files/.gitignore

Merge after previous PR (#18) as this uses it.

Download a file

---

lib/steps.js
package.json

You'll have to uncomment two lines, each individually, to see the new error messages in action if you so choose.
Fixes #17

Improves feedback for question id step. See MADE matching branch. Fix #17

---

lib/steps.js
package.json

npm v0.4.51.dnld-2 and corresponds with https://github.com/plocket/docassemble-MAEvictionDefense/tree/download_language_agnostic

Implement language agnostic downloading

---

lib/scope.js
lib/steps.js
package.json

This may conflict with the language-generating PR (#51). Should be able to test this with any interview. MADE is having a bit of extra trouble with this, especially in github. See https://github.com/plocket/docassemble-MAEvictionDefense/actions/runs/389971882
We should update the version to .61 before merging and then publish that version.

Retry first interview step to give it extra chances to load. Close #52

---

lib/steps.js
package.json

Can run test for functionality with MADE branch https://github.com/plocket/docassemble-MAEvictionDefense/tree/screenshot_dev. Package already published.

Add screenshot step with named screenshots capability

---

lib/steps.js
package.json

I don't know how to set up a test for this one right now. I came to these from development for language-agnostic test support in https://github.com/plocket/docassemble-cucumber/tree/a_lot. Because defaults weren't set, some `showif`s came up that hadn't otherwise come up. I don't recall where along the way that happened.
We probably need to update the testing suite for this repo and in doing that, figure out a smoother way to integrate a testing process somehow.

Add some `showif` functionality

---

pushing_testing_files/package.json
pushing_testing_files/run_form_tests.yml

Fix json scripts

---

pushing_testing_files/run_form_tests.yml

All these little pieces to put together. Sheesh.

Easy PR. Fix which script being used in workflow

---

lib/utils/langs.js
package.json

See action (should pass) on MADE: [ [https://github.com/plocket/docassemble-MAEvictionDefense/actions/runs/423521377]( https://github.com/plocket/docassemble-MAEvictionDefense/actions/runs/423521377) at 11 am]  ~[https://github.com/plocket/docassemble-MAEvictionDefense/actions/runs/423496961 10:45am] https://github.com/plocket/docassemble-MAEvictionDefense/actions/runs/423333291. Should be done by... 9:30am?~
[And now I forgot to implement flag and update the package version. Love it!]

In lang file creation, delete old language files before making new ones

---

lib/scope.js
lib/steps.js
package.json

See https://github.com/plocket/docassemble-MAEvictionDefense/actions/runs/428365746 at around 10:30 am.
Closes #66.

Allow setting of any variable, close #66

---

lib/utils/langs.js

#111 replace spaces with underscores in language tags

---

lib/scope.js
package.json

We'll deal with merge conflicts after the previous PR is merged so we can update to an appropriate version number. Maybe we should look into automating publishing on merge to `main` (https://github.com/plocket/docassemble-cucumber/issues/105).

Fix bug with field-finding error detection, improve err msg. (quick PR after #107)

---

.github/workflows/push_generated_testing_files_nonworkflow.yml
pushing_testing_files/.env-example
pushing_testing_files/env-example.sh

add .env-example

---

.github/workflows/test_tests.yml
.gitignore
package-lock.json
package.json
tests/features/example_test.feature

Close #124. Use https://github.com/plocket/docassemble-ALAutomatedTestingTests to test the functionality of this testing library.
Not completely sure about the workflow file.

Close #124, add automated testing for this testing library

---

lib/scope.js
lib/steps.js
tests/features/generated_story_tables.feature

Test for this branch should error (user got an error) instead of getting stuck in
infinite loop. https://github.com/plocket/docassemble-cucumber/runs/2099929359?check_suite_focus=true
We should set up some ways to assert errors happen for this repository. Not sure how exactly. Some kind of step that causes a try/catch to throw vs. not throw or something?

Fix infinite loop caused when table button var causes user errors

---

lib/scope.js
tests/unit_tests/getMatchingRow.test.js
tests/unit_tests/getPageData.test.js
tests/unit_tests/html.fixtures.js
tests/unit_tests/matches.fixtures.js
tests/unit_tests/page_data.fixtures.js
tests/unit_tests/tables.fixtures.js

#158, add yesnomaybe buttons and unit test them

#158 yesnomaybe

---

lib/scope.js
tests/unit_tests/getMatchingRow.test.js
tests/unit_tests/getPageData.test.js
tests/unit_tests/html.fixtures.js
tests/unit_tests/matches.fixtures.js
tests/unit_tests/page_data.fixtures.js
tests/unit_tests/tables.fixtures.js

#158 Add and test custom continue buttons that are not yesno or yesnomaybe

#158 custom continue buttons that are not yesno or yesnomaybe

---

package.json

Add unit tests to the rest of the tests

---

CHANGELOG.md
lib/scope.js
lib/steps.js
package.json
tests/unit_tests/getMatchingRow.test.js
tests/unit_tests/getPageData.test.js
tests/unit_tests/html.fixtures.js
tests/unit_tests/matches.fixtures.js
tests/unit_tests/page_data.fixtures.js
tests/unit_tests/tables.fixtures.js

Fixes #190 and other items listed in CHANGELOG.md. We can go through this together if needed. In trying to get DBD2 to pass, I'm running into bugs and needed behavior changes in the new code. It's the perfect interview with lots of weird edge cases!
I thought it would just a couple things and lost track. There's more to do, but I'm making this PR before this gets bigger. I've added a couple unit tests to cover some of the fixes and I'm making issues on the testing interview repo for adding fields to test against a live interview.

Too many fixes. Fixes #190, but other bugs found. Outlined in CHANGELOG.

---

CHANGELOG.md
lib/scope.js
lib/steps.js
package.json
tests/unit_tests/getMatchingRow.test.js
tests/unit_tests/getPageData.test.js
tests/unit_tests/html.fixtures.js
tests/unit_tests/matches.fixtures.js
tests/unit_tests/page_data.fixtures.js
tests/unit_tests/tables.fixtures.js

Adds unit tests as well. Turns out our map was overriding itself, exactly as we had been trying to avoid...

Fix incorrect truthy test, some small cleanup (sorry)

---

lib/github_integration/puppeteer-utils.js

Closes #20 
This is what it looks like when I create multiple projects with the same branch:

Use a unique project name

---

CHANGELOG.md
lib/scope.js
package.json
tests/unit_tests/getMatchingRow.test.js
tests/unit_tests/getPageData.test.js
tests/unit_tests/html.fixtures.js
tests/unit_tests/matches.fixtures.js
tests/unit_tests/page_data.fixtures.js
tests/unit_tests/tables.fixtures.js

Fixes #215 and adds unit tests for the fix. You can see it working here: https://github.com/SuffolkLITLab/docassemble-209aPlaintiffMotionToModify/actions/runs/764111750

Fix #215, handle object dropdowns, add unit tests.

---

CHANGELOG.md
lib/steps.js
tests/features/observation_steps.feature

Test and fix observational steps for detecting user errors

---

CHANGELOG.md
tests/features/assembly_line.feature

Add Assembly Line-specific Step tests

---

CHANGELOG.md
lib/scope.js
tests/unit_tests/getMatchingRows.test.js
tests/unit_tests/matches.fixtures.js
tests/unit_tests/tables.fixtures.js

Also had to add funcitonality to report, so started testing report
Gave warning to dev about multiple table rows matching

Implement new more comprehensive field matching data structure.

---

CHANGELOG.md
lib/scope.js
lib/steps.js
tests/features/interactive_steps.feature
tests/features/observation_steps.feature
tests/unit_tests/getMatchingRows.test.js
tests/unit_tests/matches.fixtures.js
tests/unit_tests/page_data.fixtures.js
tests/unit_tests/tables.fixtures.js

Also some cosmetic stuff.
Basically, starts making moves towards PR #265. Taking it a bit slower.
[Sorry, I meant the last changes to apply to a different branch. Let me know if I should split this.]
[Close #262, message to dev about matching rows.]

Make node specifiers more specific, add another debug log.

---

CHANGELOG.md
lib/scope.js
lib/steps.js
package.json
tests/features/interactive_steps.feature

Close #263, remove use of `scope.getField()`

---

CHANGELOG.md
lib/scope.js
lib/steps.js
package.json
tests/features/observation_steps.feature
tests/features/story_table_formats.feature
tests/features/story_tables.feature
tests/unit_tests/html.fixtures.js
tests/unit_tests/matches.fixtures.js
tests/unit_tests/normalizeTable.test.js
tests/unit_tests/tables.fixtures.js

Close #285, switch sought to trigger

---

CHANGELOG.md
lib/steps.js
package.json
tests/features/observation_steps.feature
tests/features/story_table_formats.feature
tests/features/story_tables.feature

Allow 'I get to' for the story table Step. Needed for better docs

---

lib/scope.js
package.json
tests/unit_tests/tables.fixtures.js

#220. Moves the responsibility into `scope.processVar()`. Let me know what you think.

Switch how loop incrementation is done.

---

CHANGELOG.md
lib/scope.js
package.json
tests/features/story_tables.feature
tests/unit_tests/ensureSpecialRows.test.js
tests/unit_tests/special_rows.fixtures.js
tests/unit_tests/tables.fixtures.js

Closes #220 again. See [description of behavior there](https://github.com/plocket/docassemble-cucumber/issues/220#issuecomment-866418428). If you have thoughts, I'd welcome an opinion on this alternative alongside the opinions described there.

Uses `.target_number` to handle loops. Close #220.

---

lib/scope.js
tests/features/observation_steps.feature

Closes #287 
Not sure I wrote the test correctly or put it in the right place.

Allow filenames to end with .yml

---

lib/scope.js

Remove check for elem's existance

---

lib/scope.js

Remove unused function

---

lib/steps.js

Remove unused variable

---

lib/scope.js
lib/steps.js

In an effort to refactor out the stuff that isn't shared between
the functions that call `setField`

Move `ensureSpecialRows` call up out of `setFields`

---

CHANGELOG.md
lib/scope.js
lib/steps.js
package.json
tests/features/reports.feature
tests/features/reports.fixtures.js
tests/features/test.js

this actually passes on integrated tests too. Locally, it has one
failed step and shows as otherwise passing (scenario and whole test)
Adds Steps for internal testing. Not sure if we need to differentiate these somehow. I hope I gave them names that are clear enough if seen by regular developers, though regular devs are unlikely to be looking at this code.
Close #312

Close #312, Tests a report for an unexpected failure. We'll see if

---

lib/scope.js

Remove old comment

---

lib/scope.js

Add comment explaining error detection

---

lib/scope.js

Add checkbox documentation

---

lib/scope.js

Make sure only strings are base64ed

---

CHANGELOG.md
lib/scope.js
lib/steps.js
tests/features/establishing_steps.feature
tests/features/observation_steps.feature

Close #325. Also tweak some internal test settings to make tests
smoother
Changelog has a bit more detail.

List failed scenarios first in report, fix some page ids missing in report

---

lib/scope.js
lib/steps.js
tests/features/reports.fixtures.js

Close #313, add exception messages to reports.
Close #314, add auto-prefixes to some types of report lines.
Also adds some newlines/formatting to some messages to make those bits a bit shorter and more distinct.

#313, #314, Insert exception error messages into the reports as well

---

README.md
lib/utils/env_vars.js
tests/unit_tests/env_vars.test.js

I have added code to validate that all environment variables are present and present readable error messages to the user.   This code does not test the correctness of the values of the environment variables.
Close #94.

Issue 94 - Now with Presence Validators for All Environment Variables

---

lib/steps.js

Set default timeout before each scenario starts

---

CHANGELOG.md
README.md
lib/scope.js
lib/steps.js
package.json
tests/unit_tests/fields.fixtures.js
tests/unit_tests/getAllFields.test.js
tests/unit_tests/getMatchingRows.test.js
tests/unit_tests/html.fixtures.js
tests/unit_tests/matches.fixtures.js
tests/unit_tests/tables.fixtures.js

Also seemed to come with a lot of timeout issues that this addresses as well. The changelog is pretty thorough about the work in here. This will bump us to v3.
There are ~a lot of~ [some] substantial changes, [though most of the files are just test fixtures, etc.]. Let me know if we should go through this together.
Closes #389.
Also, I'm not sure if this accidentally increments and infects v2 with these changes, so we need to check that out and possibly peel back v2 to an appropriate commit.

Close #389, update dom to Bootstrap 5

---

CHANGELOG.md
package-lock.json
package.json

Closes #396. You can see an explanation in the issue.

Close #396 for v3, move cucumber to plain dependencies (not peer)

---

CHANGELOG.md
action.yml

Closes #441. Merging it into `main` as well. Not yet sure how to develop multiple stable releases, but giving it a shot. Will update releases/v3 when this is merged to catch it up with main before the big divergence.

Create/overwrite package.json with our action.yml, closes #441

---

CHANGELOG.md
action.yml
lib/scope.js
lib/steps.js
package.json
tests/features/establishing_steps.feature

main on v3. No review needed as this has already been reviewed.

Update v4 to main. Things haven't diverged yet, but we may stop using main soon, or keep

---

lib/scope.js
lib/steps.js
package-lock.json
package.json
tests/features/reports.feature
tests/unit_tests/getSafeScenarioBaseFilename.fixtures.js
tests/unit_tests/getSafeScenarioBaseFilename.test.js
tests/unit_tests/getSafeScenarioFilename.test.js
tests/unit_tests/names.fixtures.js

Closes #371? 
I'm not sure what is required for this ticket. The function mentioned in the issue is already working as it should be. I added a test to confirm. 
[This has already been reviewed when #463 was merged.]

Separate Scenario filenames, ids, and report headers for v3

---

CHANGELOG.md
lib/scope.js
lib/steps.js
tests/features/observation_steps.feature
tests/features/reports.feature

Also:
- Downloads page's JSON vars to .json file in "downloads" artifacts.
- Adds tests for the step and its error report.
Addresses #470 for v3. Will have to do the same for v4 before closing.

Add v3 Step to compare JSON page var string value to given str value 

---

CHANGELOG.md
lib/scope.js
lib/steps.js
tests/features/observation_steps.feature
tests/features/reports.feature

Also:
- Downloads page's JSON vars to .json file in "downloads" artifacts.
- Adds tests for the step and its error report.
Closes #470 if merged after v3.

Add v4 Step to compare JSON page var string value to given str value
