lib/github_integration/install-branch.js
lib/github_integration/puppeteer-utils.js
lib/scope.js
lib/steps.js
lib/utils/env_vars.js
package.json

Had to change what was happening a bit because more was relying on them than I thought. Also, the initial page load test needed tweaking so that the file name didn't have to be provided. I think. I'm currently not sure exactly what was going on there, though it was clear to me yesterday.
It now:
1. Makes sure a `test.yml` file is generated
1. Uses that `test.yml` to make sure the server has really recovered from the `pull`
The downside is that if the developer has a custom `test.yml`, they will have to make sure it's is working.

Separate out environmental variables, improve initial page load test

---

lib/DOM.md.html
lib/scope.js
lib/steps.js
package.json

Will conflict with other branch at least because of version number, but we can work that out after those are merged.
Testing: I haven't yet figured out the process for testing this. I'm pairing it with https://github.com/SuffolkLITLab/docassemble-IntegratedTesting to test functionality, but the branches that match each others' functionality are not clear, so it's hard to see which to test with what. I guess that's a clue as to how to line up testing. Hasn't happened here, though.
I think the matching branch for this at https://github.com/SuffolkLITLab/docassemble-IntegratedTesting is `npmjs`.
Also, these tests probably won't work anyway because they try to use the `test.yml` file and that's not set up in this version of the package.

Abstract getting choice field, add notes on DOM (conflicts for sure)

---

lib/steps.js
lib/utils/env_vars.js
lib/utils/langs.js
package.json
pushing_testing_files/.gitignore
pushing_testing_files/package.json
pushing_testing_files/run_form_tests.yml

Addresses #37. Note: The package.json script is to allow local developers to test the languages. I think we should keep the non-multi-lingual tests out of github automated runs for now and they could cause tests to go for quite a long while. With that in mind, maybe the stretch goal should is a more immediate need to be brought along pretty quickly.

Add automated language testing. Only one pdf downloaded for all.

---

lib/steps.js
package.json
pushing_testing_files/run_form_tests.yml

Also uses dynamic `REPO_URL` because of issue MADE was running into.
You can see the behavior of this version and the associated artifacts for (intentional) errors, screenshots, and downloads with their file names at [this action](https://github.com/plocket/docassemble-MAEvictionDefense/actions/runs/405916344) which should be done by 8:40am ET.

Make artifact filenames more specific, move device into own step

---

lib/steps.js
lib/utils/env_vars.js
package.json

I made a branch on MADE that is deliberately likely to trigger timeout errors. In the past, some of the post-error test would have also errored because the interview would simply resume from where the last test had got it to. None of that should be happening now - just the normal timeout errors. It should be [this action](https://github.com/plocket/docassemble-MAEvictionDefense/actions/runs/406113860) that will probably be done around... 11? Feel free to run it again if you think it's warranted as this is based on race conditions.

Make sure new tests start an interview fresh

---

lib/scope.js
lib/steps.js
package.json
pushing_testing_files/.gitignore
pushing_testing_files/run_form_tests.yml

Saves a primitive report `md` file to artifacts that lists the order in which question ids appeared during each scenario.
I'm trying to figure out what ways we can give useful feedback to the developer since most of their development is meant to be in Github and their ability to get test feedback would be a bit limited.
We might later figure out how to integrate some kind of flexible reporter into the mix, but this is my attempt at an MVP. Also, the data that is printed is saved as an object and I can see it being used in the future to make assertions about the order in which the questions appeared. That would let developers be more selective about what question order they care to test (as opposed to listing out every single step in sequential order).
See action: …

Add some report capabilities to var_table

---

lib/scope.js
lib/steps.js
package.json

Should we log the report to the console? It's the only way I could figure out how to do it that wouldn't require people to download a file. I personally find it really annoying to download from actions. Or in general. Thoughts?
See action: https://github.com/plocket/docassemble-MAEvictionDefense/actions/runs/434724343

Log report to the console as well

---

lib/scope.js
lib/steps.js
package.json

Decided to embrace the id name as it really simplified stuff. (I think both for us and for the developer).
Test: ~https://github.com/plocket/docassemble-MAEvictionDefense/runs/1615705210?check_suite_focus=true~
https://github.com/plocket/docassemble-MAEvictionDefense/actions/runs/448107706

One-step for the var table with the id name

---

lib/scope.js
package.json

Button-finding causes areas when `set_to` has things like new line characters (which might occur for textareas, etc)
I won't start now in order to give preference to previous PRs, but we need to start updating the accompanying files - package.json, etc. Though I thought we were already doing that, so...

Normalize `set_to` when getting fields

---

lib/scope.js
lib/steps.js
package.json
pushing_testing_files/package.json

Closes #113
- Make getField more flexible so table columns can be
interchangable for generated tests.
- Find only enabled fields so out-of-order table steps
will not try to fill in disabled fields.
Test run: https://github.com/plocket/docassemble-MAEvictionDefense/runs/1704204877?check_suite_focus=true
[This version numbering thing is getting complicated. We should figure out a standard way to handle it.]

Make getField more flexible for generated tests. See details. Close #113

---

lib/scope.js
lib/steps.js
package.json

[Fix #79, fix #115, fix #139] Would love some better ideas for handling signing. It's a bit all over the place. Seems too coupled to me. Relatedly, I recommend reading scope.processVar by itself instead of the diff. Easier to see what's going on.
Sadly, as a consequence of these changes the tilde symbol for the signature step is gone :(
Test started at 8:40: https://github.com/plocket/docassemble-MAEvictionDefense/runs/1742130312?check_suite_focus=true

Fix continue button fields need a linear order to work. Fix #115

---

lib/scope.js
lib/steps.js
package.json

I ended up moving the signature logic to the loop that was gathering fields. The outer, `while`, loop meant a lot of complications. Tell me what you think.
Also added remaining vars to the report. It's not quite in the right spot, but it does let us see if the signature solution is working. See https://github.com/plocket/docassemble-MAEvictionDefense/actions/runs/528828913

Move logic to field gathering loop, report on remaining vars

---

lib/scope.js
package.json

Fixes #149. See [passing test](https://github.com/SuffolkLITLab/docassemble-209aPlaintiffMotionToModify/runs/1846167660?check_suite_focus=true).
Sorry that I changed a var name. That happened along the way and I forgot to change it back.

Fix #149, dropdown options created from objects are not selected

---

lib/steps.js
package.json

Fix #79 race conditions.
Test:
- Automated tests will fail, but should get past question id `dbd-04-levy-shared-account` (should be listed in the report). [See test here](https://github.com/plocket/docassemble-DeadBrokeDads2/runs/2014741848?check_suite_focus=true)

Fix #79, prevent new page race conditions by ensuring url change

---

lib/scope.js
package.json

Vars might be set out of order. Addresses #158, but does not close it. This will let some tests work under some circumstances. [This test shows the result](https://github.com/plocket/docassemble-DeadBrokeDads2/runs/2023969728?check_suite_focus=true) (passes).

Re #158, temp fix for simple index_var detection

---

CHANGELOG.md
lib/scope.js
lib/steps.js
package.json
tests/features/generated_story_tables.feature

[`.focus()` seemed to work locally, but doesn't seem to work on GitHub for some reason. I'll try `.scrollIntoView(false)` next.]
1. I've been getting a bit tired of adding elaborate debugging stuff every time there's weird behavior. I added stuff that will be silent, but that I use all the time - coloring the DOM nodes. That should show up on screenshots if `DEBUG=1` in SECRETS, which no one knows about yet, so it shouldn't confuse anyone.
2. Puppeteer tries to scroll up to make an element visible before interacting with it. First, [that's known to not always be successful](https://github.com/puppeteer/puppeteer/issues/6462#issuecomment-717163409). Secondly, docassemble's header actually blocks the fields when they're at the top of the screen, so we need `false` in …

Fix `.setVariable()` some elems too far out of view, add some debugging

---

lib/scope.js
tests/unit_tests/getMatchingRow.test.js
tests/unit_tests/matches.fixtures.js
tests/unit_tests/page_data.fixtures.js
tests/unit_tests/tables.fixtures.js

Addresses #158 refactor for v2. One of the next steps is being able to match a row in the table to a field. The new columns in the story table have been changed to basically `| var name | value | checked |`, though now that I think about it, 'checked' doesn't quite make sense. I'm now thinking maybe 'select' would be better, but it still doesn't seem clear for some reason.
Need to remember to normalize character case when first processing the table.

#158 Match a table row to  a field

---

lib/scope.js
tests/unit_tests/getMatchingRow.test.js
tests/unit_tests/getPageData.test.js
tests/unit_tests/html.fixtures.js
tests/unit_tests/matches.fixtures.js
tests/unit_tests/page_data.fixtures.js
tests/unit_tests/tables.fixtures.js

#158 Add and test a single continue button

#158 a single continue button

---

lib/scope.js
tests/unit_tests/getMatchingRow.test.js
tests/unit_tests/getPageData.test.js
tests/unit_tests/html.fixtures.js
tests/unit_tests/matches.fixtures.js
tests/unit_tests/page_data.fixtures.js
tests/unit_tests/tables.fixtures.js

#158 v2. This should cover this end of the v2 work for what we currently have up in the testing interview. Next will be working on plugging this into the DOM.
We may be able to make something that maps old tables to new tables, so maybe we could actually keep this as v1. It might be a bit of a pain, though, so not sure how much it's worth considering how few projects are using it atm.

#158 Add an test an action button that triggers an event

---

lib/scope.js
lib/steps.js
tests/features/generated_story_tables.feature
tests/unit_tests/normalizeTable.test.js
tests/unit_tests/tables.fixtures.js

#158. I think this will fully support v1 tables, though it is a bit awkward and its testing isn't super thorough yet because we don't have even a single signature page in the online interviews. Once that's done and added to the tests, I think we can be fairly confident this will,  except for the primitive proxy var (x, i, j...) setting,  support everything that the we were previously able to support.
Next I think we need to add unit tests to workflows and get started on proxy vars themselves.

#158 support v1 story table (after #185)

---

lib/scope.js
package.json

See tests at https://github.com/SuffolkLITLab/docassemble-MA209AProtectiveOrder/runs/2492735082?check_suite_focus=true. They will fail, but they should get to at least the question id `children-user-is-parent-of`. Don't worry about the messages there about multiple items found on the page (for now).
Custom fields will sometimes have to be handled separately. This one replaces one input date field with three other fields to make it easier to input birthdates.
Example html of the fields in their question:
```html
<section id="daquestion" class="tab-pane active col-xl-6 col-lg-6 col-md-9">
<div class="progress mt-2">
<div class="progress-bar" role="progressbar" aria-valuenow="18.549374999999998" aria-valuemin="0" aria-valuemax="100" style="width: 18.549374999999998%;"></div>
</div> …
```

Handles AL custom birthdate field

---

CHANGELOG.md
lib/steps.js
tests/features/generated_story_tables.feature
tests/features/observation_steps.feature

Close #222, close #223, close #224, close #225. Some observational steps that just examine a static page. This isn't all of them, but a lot of the others have questions or might have other functionality mixed in.
For example, I'm not sure where to put link stuff as we have a step that observes what the link is and a step that checked that the link leads to a working page.

Add page-arrival static observation step tests

---

lib/steps.js
tests/features/interactive_steps.feature

fix 'sign' step as I found it to be broken. Need to note that none
of the tests currently test the action button in the testing
interview.
[After these test are written, we can convert this step to use the new field setting methodology that the table is using.]

Close #241, close #251, interactive steps 'set' and 'sign'. Also,

---

CHANGELOG.md
lib/scope.js
lib/steps.js

These are steps I think nothing is using and/or are redundant now.
It removes a lot of steps that depend on visible text as opposed
to things that won't change when translated.
Also comments out checking value of checkbox for now as I think
it will need major changes and hasn't been used by anyone.
Closes #238, closes #240, closes #244
Addresses #227

Remove unused steps and then unused scope stuff, clean a bit.

---

CHANGELOG.md
lib/steps.js
tests/features/observation_steps.feature

Addresses #234 and #235. I realize this adds a step, but when we make sure the other two link checking steps aren't being used, I think it'd be best to remove them and stick with this one.

Add language-agnostic link-url checking step and its test

---

CHANGELOG.md
lib/scope.js
tests/features/observation_steps.feature
tests/features/story_table_formats.feature
tests/features/story_tables.feature
tests/unit_tests/matches.fixtures.js
tests/unit_tests/page_data.fixtures.js
tests/unit_tests/tables.fixtures.js

Which removes the need for the `checked` column.
- Remove the need for the `checked` story table column and prop by: 1) Moving the `value` of checkboxes into their var name column. 2) Moving the `checked` value of checkboxes into the `value` column.
- Combined checkbox encoding matching regex into one regex.
- Regex testing for match to proxy var - both the regex itself being more strict and the test for a match being more predictable.
Also removed rows from a feature test using a story table. They weren't needed and were confusing to run into.
Addresses #264 and #242.
[Close #271 (proxy var matching regex duplicate), close #270 (/sign), close #261  (proxy var matching regex)]

Combine checkbox value with var name for a full dict var name

---

.gitignore
lib/github_integration/install-branch.js
lib/github_integration/puppeteer-utils.js
lib/scope.js
lib/steps.js
lib/utils/env_vars.js

Saves the name in a file. I think GitHub actions won't need
anything more because we're not trying to save this as an artifact.
Added lots of console logs, though some are just for debugging.
Close #275 (delete correct project), closes #100 (improve setup success message), closes #210 (tweak name incrementation), addresses #94 (improve logs)

Close #275, persist name of created project so it can be deleted

---

CHANGELOG.md
lib/scope.js
package.json
tests/features/interactive_steps.feature
tests/features/story_table_formats.feature
tests/features/story_tables.feature
tests/unit_tests/fields.fixtures.js
tests/unit_tests/getAllFields.test.js
tests/unit_tests/getMatchingRows.test.js
tests/unit_tests/html.fixtures.js
tests/unit_tests/matches.fixtures.js
tests/unit_tests/tables.fixtures.js

This is just the MVP for supporting this kind of loop, but it'll be sufficient for now. The developer will have to add this row in this way to their table:
```
|  x.there_is_another  | 3 | some_var.there_is_another |
```
This will indicate to make 3 `some_var` items. Literally, it means the test will answer 'yes' to the `.there_is_another` question two times (the question isn't asked the first time).
It's kind of confusing whether to give the number of items you want or the number of button presses you want. I'm not sure which to pick or if there's a better way to indicate it.
Closes #220 MVP
[Also starts to move `sought` to `trigger` - that's a conversion that will happen next/soon.]
Close #183.

Close #220 MVP, support a `.there_is_another` loop, but only with explicit dev values

---

lib/scope.js
tests/features/story_tables.feature

Re: #220 basically. Changes the table so `.there_is_another` values actually represent the number of times that the user would need to press the `.there_is_another` button.

Switch loop value to be number of `.there_is_another` btn presses

---

lib/scope.js
lib/steps.js
package-lock.json
package.json
tests/unit_tests/getSafeScenarioFilename.test.js
tests/unit_tests/names.fixtures.js

#141, but only the filenames part. This has been a while coming I think. Not all developers would know that their scenario's description needs to be safe for a filename. It's also a safe directory name, but I _think_ filenames are safe directory names, right?
Replace invalid chars with one '_' each. There isn't really a more refined way to do it without adding a lot of cruft if we want to respect any duplicate `_`s in the prefix that's passed in.

Addresses #141, safe names - sanitize filenames

---

lib/scope.js

Closes #167 
The ticket asked for the `Buffer` usage to be rewritten, but we have a nice new function that works properly so I think we can just use that instead. Let me know if that's incorrect.

Remove deprecated reference to Buffer, unused function

---

lib/scope.js
lib/steps.js

No particular issue. Part of the clean-up process. The name `setFields()` is very like `setField()`, but I'm hoping to phase out the latter sometime soon and `setFields()` makes a lot more sense for this function. Maybe it should be `setFieldsOnPage()`? Thoughts?

Simplify and rename scope.processVar()

---

CHANGELOG.md
lib/scope.js
package.json
tests/unit_tests/html.fixtures.js

all the AssemblyLine projects would have to be updated at once
along with their version change and I'm not sure of all the
projects that would affect. Otherwise, any new pushes to them
would cause useless failing tests.

Add backwards compatibility for `#sought_var` element because

---

CHANGELOG.md
lib/scope.js
lib/steps.js
package.json
tests/features/assembly_line.feature
tests/features/observation_steps.feature
tests/features/reports.feature
tests/features/reports.fixtures.js
tests/features/story_tables.feature
tests/features/test.js
tests/unit_tests/getSafeScenarioFilename.test.js
tests/unit_tests/names.fixtures.js

Address #138 (may close it too, upon discussion). Notes and caveats also covered in #138:
- End of table report is chronological so that people can copy/
paste it into their files if desired - alphabetical listing of
vars is recommended. (most useful for used vars)
- Problem with double char escaping (e.g. \\n) with Steps, but
avoids accidental new lines from story table strings.
- While running tests, page continuation symbol is printed in
during-test output, even if an error is about to be thrown for that
page. (problem?)
- All vars are displayed as table rows, even if a Step was used.
- Report shows original row, not the rows actually used in the
table. The concern is that it will be confusing otherwise, even
though it then gives less insight into what may have happened wrong
so we'll …

Re: #138, Add variable information to reports

---

CHANGELOG.md
lib/scope.js
lib/steps.js
package.json
tests/features/establishing_steps.feature

Shortens it because now devs who need more time can add it. It
makes an assumption about how long most interviews will need and
we'll have to see if that bears out. Default timeout is now 30secs
~It does lengthen our own tests by a chunk, unfortunately.~ [Actually, it shortens them by a bit in some ways because the default wait time is cut down!]
Closes #317.

Close #317, Add custom timeout Step. Also shortens default timeout

---

CHANGELOG.md
lib/scope.js
package.json

I assumed puppeteer would take care of waiting, but it turns out that it does not. Gave me a chance to use Promises differently, though. It's nice to see their asynchronicity be useful for a change.

Hotfix: Wait for files to finish uploading before finishing upload Step

---

CHANGELOG.md
lib/scope.js
lib/steps.js
package.json
tests/features/reports.feature

This is an alternative to #354.
Allows testing multiple strings separately for one scenario, but excludes testing failing or passing. I'm not sure about it, but it does narrow the scope of this Step to one thing.
Is there a danger a Scenario would include the desired text, would be expected to pass, but would actually fail, and this wouldn't catch that? Should there be a separate 'the status of this Scenario is passing/failed' Step? I'm not sure. It just seemed conflated to have them both in the same Step.
(I think I accidentally pushed something to the other branch that I hadn't quite intended to, so you'll see some deletion of commented out code from that one. If we want to take this branch instead of #354, we should switch this to a PR on main. That way we can then review the changes …

#355, implement some report tests, alternative to #354

---

lib/scope.js
lib/steps.js
tests/features/reports.feature

Interested in input on this one - is it easier to maintain/read when the expected report text is in the `.feature` file itself, or does it just make things messy?
Also change Steps so that all report steps get checked in `After()` so that final parts of the Scenario report get added. Not sure it's completely necessary and would be interested in feedback on that too.

Show how fixtures could be in actual .feature file

---

CHANGELOG.md
lib/scope.js
package.json

I think the math is more simple now. I hope. It again wasn't quite the right thing before. This only gives two attempts at loading, but it does use fully half the allotted time to do so, which might be a good enough compromise - gives more time for the server to load. I dunno.

Hotfix. Move load check so it doesn't error. Change the way repeated loading is attempted.

---

CHANGELOG.md
lib/github_integration/puppeteer-utils.js
lib/scope.js
package.json

needs to give a chance for the module to reload. Also, added
another check to the setup pull as per instructions. See issue
comment for details. That should supposedly help this not happen,
but I did add a line in the report if it still happens and we'll
hopefully be able to see if that's not working and then report on
it.
Hope these are enough to fix this problem finally, but I still don't know
of a way to test this reliably.
Close #367

Close #367, fix erroring too soon on no module error which

---

lib/scope.js
package.json

Address https://github.com/plocket/docassemble-cucumber/pull/368#discussion_r683079473, though not in the described way. Keeping the check in the `catch`, as we want to handle errors there too, and adding global timeout to that check.

Add check for global timeout along with attempts count check.

---

lib/steps.js
tests/features/assembly_line.feature
tests/features/observation_steps.feature

* Then I cannot continue
* Then I do not continue
* Then I can’t continue (using a Unicode apostrophe)
* Then I don’t continue (ditto)
This should make it easier to copy and paste test steps from a PDF or
Word.
Closes #152

Updated the "Then I can't continue" step with the following variants:

---

CHANGELOG.md
lib/github_integration/install-branch.js
lib/github_integration/puppeteer-utils.js
package.json

Closes #417. Other than the title, the details are in the issue itself. This includes a workaround for a current da bug. This is already published to allow folks to work with their private repos, but it can still be improved and changed based on review.

Close #417, fix private repos don't get pulled into package

---

CHANGELOG.md
action.yml

It's a composite action. The corresponding user action will be
added to the setup interview. This doesn't break anything that's
working now, just sets us up to provide the simpler workflow in
the future.
Closes #420, though the unanswered questions in there should be
turned into their own issue(s)
Still to be answered:
How do we version this? At least for this first bit. Shall we make a tag release now and, for now, just keep updating it? I think we really need automation to make this workflow work. See https://github.com/SuffolkLITLab/ALKiln/issues/420#issuecomment-993959965 and possibly additional relevant questions there.

Close #420, simplify subscriber workflow with our own action

---

CHANGELOG.md
lib/scope.js
lib/steps.js
package.json
tests/features/establishing_steps.feature

Close #449, can't add url parameters/url arguments to interview name. Let me know if this seems robust enough.
[Also noticed typo in error message. That should probably have been saved for some bit typo PR, so I can remove it if preferred.]

Fix interview name not allowing url parameters

---

lib/scope.js
lib/steps.js
package-lock.json
package.json
tests/features/reports.feature
tests/unit_tests/getSafeScenarioBaseFilename.fixtures.js
tests/unit_tests/getSafeScenarioBaseFilename.test.js
tests/unit_tests/getSafeScenarioFilename.test.js
tests/unit_tests/names.fixtures.js

Basically, I looked at this and it seemed like maybe it was time for a bigger change. Instead of putting numbers in scenario headers and/or adjusting tests to allow those to pass, I'm trying to make a more extensive change to how we're managing that whole system.
Adds base-scenario-file-name creation and adds tests for that too.
Uses "-" as separator for major items as long as it doesn't break our .gitignore and artifact-getting name matching in the workflows. A change in that will have to wait for a breaking version.
For #371.

Separate Scenario report heading vs. filename vs scenario id

---

lib/scope.js
lib/steps.js
package-lock.json
package.json
tests/features/reports.feature
tests/unit_tests/getSafeScenarioBaseFilename.fixtures.js
tests/unit_tests/getSafeScenarioBaseFilename.test.js
tests/unit_tests/getSafeScenarioFilename.test.js
tests/unit_tests/names.fixtures.js

Separate Scenario filenames, ids, and report headers
Same as #382. Closes #371. This has already been reviewed when #463 was merged.

Separate Scenario filenames, ids, and report headers for v4

---

CHANGELOG.md
action.yml
package-lock.json
package.json

Because it's a security issue, I already published it. ~I think. I'd love a double check on this because I published before I committed and I don't recall if that flow is sufficient.~ I'm just going to check it myself. Faster that way.
See https://www.bleepingcomputer.com/news/security/dev-corrupts-npm-libs-colors-and-faker-breaking-thousands-of-apps/
We don't use other libraries mentioned in there, so we're good on those.

Security: Pinned colors library to 1.4.0

---

CHANGELOG.md
lib/steps.js
tests/features/observation_steps.feature

other JSON step because I need to publish this one. It's already been
field tested by the user who requested it, so I'm going to forgo
a review in order to be able to move this forwards.
That is, the other Step is in a PR under review and I don't know
when someone will have time to take a look.
Addresses #454 for v3. Won't close till it's added to v4.
[Will wait till tests have passed.]

Add step to get page's vars and vals for v3. Unintegrated with the

---

CHANGELOG.md
lib/steps.js
tests/features/observation_steps.feature

other JSON Step because I need to publish this one and the other
is in an unreviewed PR and I don't know when someone will have
time to take a look. It's already been field tested by the user
who requested it, so I'm going to forgo a review in order to be
able to move this forwards.
Addresses #454. Have to save to artifacts before the issue gets closed.
Will wait till tests have passed.

Add Step to get page's vars and vals for v4. Unintegrated with the

---

lib/scope.js
lib/steps.js
tests/features/establishing_steps.feature

This adds a temporary function for waiting in scope.js that will soon be replaced by a singular function in the utils folder. That said, that function is part of v4 changes, and this can improve v3 as well, so we might as well not wait.
Addresses #387, after a little confusion. Should add this to the testing docs as a 'first step' after this is merged.
[Also, generally adds safety measures for when `page` does not exist.]
[v4 has to wait till API PR is accepted.]

Allow a developer to wait as a first Step for v3. Address #387. Add test.

---

action.yml

The comments there are supposed to contain code that our users (developers) can copy/paste into their file. Right now if they do that their file will fail. This will fix that.

Remove failing `description` in example comment in action.yml

---

lib/steps.js

Just following up those two JSON updates that had to be independent of each other.
Won't be doing this for v3. Focusing on moving to v4.

Re-use json function for both string comparison and report log for v4

---

action.yml

The comments there are supposed to contain code that our users (developers) can copy/paste into their file. Right now if they do that their file will fail. This will fix that.

Remove failing `description` in copy/paste example in action.yml
